# makefile for Figure 10d

PLOTNAME = Fig10d

SIZE = 5in,3.25in
FONT = Helvetica
FONTSIZE = 10
GNUPLOT_SCRIPT = Fig10d_MPE.plt

datafiles = Fig10d_therm.dat \
	    Fig10d_photo.dat

include ../common.mk

