# makefile for Figure 6

PLOTNAME = Fig6

SIZE = 5in,3.25in
FONT = Helvetica
FONTSIZE = 10
GNUPLOT_SCRIPT = Fig6_UV_IR_MPE.plt

datafiles = Fig6_IR_MPE_Data.dat \
	    Fig6_UV_MPE_Data.dat

include ../common.mk

