# makefile for Figure 10b

PLOTNAME = Fig10b

SIZE = 5in,3.25in
FONT = Helvetica
FONTSIZE = 10
GNUPLOT_SCRIPT = Fig10b_MPE.plt

datafiles = Fig10b_therm.dat \
	    Fig10b_photo.dat

include ../common.mk

