# makefile for Figure 10c

PLOTNAME = Fig10c

SIZE = 5in,3.25in
FONT = Helvetica
FONTSIZE = 10
GNUPLOT_SCRIPT = Fig10c_MPE.plt

datafiles = Fig10c_therm.dat \
	    Fig10c_photo.dat

include ../common.mk

