# makefile for Figure 10e

PLOTNAME = Fig10e

SIZE = 5in,3.25in
FONT = Helvetica
FONTSIZE = 10
GNUPLOT_SCRIPT = Fig10e_MPE.plt

datafiles = Fig10e_therm.dat \
	    Fig10e_photo.dat

include ../common.mk

