# makefile for Figure 3b

PLOTNAME = Fig3b

SIZE = 4in,3in
FONT = Helvetica
FONTSIZE = 10
GNUPLOT_SCRIPT = Fig3b_Cg.plt

include ../common.mk

#$(output_file) : $(GNUPLOT_SCRIPT)
#	gnuplot \
#	    -e $(term_cmd) \
#	    -e $(font_cmd) \
#	    -e $(output_cmd) \
#	    $(GNUPLOT_SCRIPT)

